services:
  postgres:
    image: postgres:16
    container_name: airbnb_clone_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: airbnb_clone_db
    ports:
      - '5433:5432'
    volumes:
      - airbnb_clone_db:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres -d airbnb_clone_db']
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  airbnb_clone_db:
